[package]
name = "backend"
version = "0.1.0"
authors = ["Peter Cai <peter@typeblog.net>"]

[dependencies]
actix = "0.7"
actix-web = "0.7"
byteorder = "1.2"
futures = "0.1"
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"
sled = "0.15"
tokio = "0.1"
tokio-threadpool = "0.1"