[package]
name = "backend"
version = "0.1.0"
authors = ["Peter Cai <peter@typeblog.net>"]

[dependencies]
actix-web = "0.7"
byteorder = "1.2"
futures = "0.1"
sled = "0.15"
tokio = "0.1"
tokio-threadpool = "0.1"